In [1]:
#importing libraries
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
from sklearn import svm
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split

In [3]:
#importing dataset
data=pd.read_csv('SVM_glass.csv')
data.head()

Id       RI     Na    Mg    Al     Si     K    Ca   Ba   Fe  Type
0   1  1.52101  13.64  4.49  1.10  71.78  0.06  8.75  0.0  0.0     1
1   2  1.51761  13.89  3.60  1.36  72.73  0.48  7.83  0.0  0.0     1
2   3  1.51618  13.53  3.55  1.54  72.99  0.39  7.78  0.0  0.0     1
3   4  1.51766  13.21  3.69  1.29  72.61  0.57  8.22  0.0  0.0     1
4   5  1.51742  13.27  3.62  1.24  73.08  0.55  8.07  0.0  0.0     1

In [4]:
StandardScaler().fit_transform(data)

array([[-1.72397593,  0.87286765,  0.28495326, ..., -0.35287683,
        -0.5864509 , -0.84827468],
       [-1.70778837, -0.24933347,  0.59181718, ..., -0.35287683,
        -0.5864509 , -0.84827468],
       [-1.6916008 , -0.72131806,  0.14993314, ..., -0.35287683,
        -0.5864509 , -0.84827468],
       ...,
       [ 1.6916008 ,  0.75404635,  1.16872135, ...,  2.95320036,
        -0.5864509 ,  2.01047778],
       [ 1.70778837, -0.61239854,  1.19327046, ...,  2.81208731,
        -0.5864509 ,  2.01047778],
       [ 1.72397593, -0.41436305,  1.00915211, ...,  3.01367739,
        -0.5864509 ,  2.01047778]])

In [5]:
X=data.drop('Type',axis=1)
Y=data.Type

In [6]:
model=svm.SVC(kernel='linear')
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.3)
model.fit(X_train,Y_train)     

SVC(kernel='linear')

In [7]:
model.support_vectors_

array([[6.90000e+01, 1.52152e+00, 1.31200e+01, 3.58000e+00, 9.00000e-01,
        7.22000e+01, 2.30000e-01, 9.82000e+00, 0.00000e+00, 1.60000e-01],
       [7.10000e+01, 1.51574e+00, 1.48600e+01, 3.67000e+00, 1.74000e+00,
        7.18700e+01, 1.60000e-01, 7.36000e+00, 0.00000e+00, 1.20000e-01],
       [7.20000e+01, 1.51848e+00, 1.36400e+01, 3.87000e+00, 1.27000e+00,
        7.19600e+01, 5.40000e-01, 8.32000e+00, 0.00000e+00, 3.20000e-01],
       [1.46000e+02, 1.51839e+00, 1.28500e+01, 3.67000e+00, 1.24000e+00,
        7.25700e+01, 6.20000e-01, 8.68000e+00, 0.00000e+00, 3.50000e-01],
       [1.47000e+02, 1.51769e+00, 1.36500e+01, 3.66000e+00, 1.11000e+00,
        7.27700e+01, 1.10000e-01, 8.60000e+00, 0.00000e+00, 0.00000e+00],
       [1.63000e+02, 1.52211e+00, 1.41900e+01, 3.78000e+00, 9.10000e-01,
        7.13600e+01, 2.30000e-01, 9.14000e+00, 0.00000e+00, 3.70000e-01],
       [1.73000e+02, 1.51321e+00, 1.30000e+01, 0.00000e+00, 3.02000e+00,
        7.07000e+01, 6.21000e+00, 6.93000e+00

In [8]:
model.n_support_

array([1, 3, 2, 4, 3, 1])

In [9]:
Y_pred=model.predict(X_test)

print("Accuracy\n",accuracy_score(Y_test,Y_pred))
print("\nConfusion Matrix\n",confusion_matrix(Y_test,Y_pred))
print("\nClassification Report\n",classification_report(Y_test,Y_pred))

Accuracy
 1.0

Confusion Matrix
 [[20  0  0  0  0  0]
 [ 0 17  0  0  0  0]
 [ 0  0  7  0  0  0]
 [ 0  0  0  6  0  0]
 [ 0  0  0  0  2  0]
 [ 0  0  0  0  0 13]]

Classification Report
               precision    recall  f1-score   support

           1       1.00      1.00      1.00        20
           2       1.00      1.00      1.00        17
           3       1.00      1.00      1.00         7
           5       1.00      1.00      1.00         6
           6       1.00      1.00      1.00         2
           7       1.00      1.00      1.00        13

    accuracy                           1.00        65
   macro avg       1.00      1.00      1.00        65
weighted avg       1.00      1.00      1.00        65



In [10]:
#different models
model1=svm.SVC(kernel='sigmoid')
model2=svm.SVC(kernel='poly')
model3=svm.SVC(kernel='rbf')

#training model
model1.fit(X_train,Y_train)
model2.fit(X_train,Y_train)
model3.fit(X_train,Y_train)

SVC()

In [11]:
#accuracy of models
Y_pred1=model1.predict(X_test)
Y_pred2=model2.predict(X_test)
Y_pred3=model3.predict(X_test)

print("Accuracy of Model1 : \n",accuracy_score(Y_pred1,Y_test))

print("\nAccuracy of Model2 : \n",accuracy_score(Y_pred2,Y_test))

print("\nAccuracy of Model3 : \n",accuracy_score(Y_pred3,Y_test))

Accuracy of Model1 : 
 0.47692307692307695

Accuracy of Model2 : 
 0.9538461538461539

Accuracy of Model3 : 
 0.7384615384615385
